### PR TITLE
Updated the required changes for "About us" section

### PR DESCRIPTION
**Pull request by Sarthak-Mittal**
- I tried to change opacity of image from class 'bg-aboutUs' in grascale.css, but it was affecting the child elements also. I couldn't figure out another way possible, so i ended up editing the image itself.
- Done with other minor changes.

### CODE REVIEW

**Comment by FlameFractal** [comment]
https://sarthak-mittal.github.io/breeze-website/

crop out krishna's name from that new edited image you added? so that it doesn't have to be done again later!

**Comment by Sarthak-Mittal** [comment]
Do you really want to crop out his name from that image.
Copyright issues and stuff(you sure @FlameFractal ?)

**Comment by FlameFractal** [comment]
I'm assuming we have his permission, right?
Someone connected with the OC please pitch in, @rhnvrm @mr-karan ..

**Comment by rhnvrm** [comment]
@Sarthak-Mittal @FlameFractal yes no issues regarding that. please crop

**Pull request merged**
